[tool.poetry]
package-mode = false
[tool.poetry.dependencies]
python = "3.12.3"
coverage = ">= 5.0.0"
pytest-timeout = "*"
pytest-cov = "*"
coverage-sbfl = "*"
flitsr = "2.3.0"
setuptools = "<=81.0.0"

[tool.poetry.group.dev.dependencies]
setuptools = "^81.0.0"

